name = input("Please enter your name: ")
print ('Hello ' + name)
amount1 = int(input("Please enter an amount of money in cents "))
amount2 = int(input("Thank you and please enter another amount in cents "))
print (amount1 + amount2)